# Generated by Django 5.1.2 on 2024-10-21 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("total_bill", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "billing_method",
                    models.CharField(
                        choices=[
                            ("EX", "exact"),
                            ("EQ", "equal"),
                            ("PE", "percentage"),
                        ],
                        default="EQ",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnedBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owes", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned",
                        to="api.expense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
