# Generated by Django 5.1.2 on 2024-10-21 18:43

import picklefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_expense_ownedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="money_owes",
            field=picklefield.fields.PickledObjectField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
