# Generated by Django 5.1.2 on 2024-10-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_expense_money_owes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="money_owes",
        ),
        migrations.DeleteModel(
            name="OwnedBy",
        ),
    ]
