# Generated by Django 5.1.2 on 2024-10-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_ownedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedby",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_by",
                to="api.expense",
            ),
        ),
    ]
