# Generated by Django 5.1.2 on 2024-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_ownedby_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedby",
            name="owes",
            field=models.CharField(max_length=20),
        ),
    ]
